<?php

namespace App\DataFixtures;

use App\Entity\City;
use App\Entity\Country;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class CityFixtures extends Fixture implements DependentFixtureInterface
{
    public const string CITY_ZAGREB = "CITY_ZAGREB";

    public function load(ObjectManager $manager): void
    {
        $citiesData = [
            // Croatia
            ["name" => "Zagreb", "latitude" => 45.8150, "longitude" => 15.9785, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Split", "latitude" => 43.5081, "longitude" => 16.4402, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Rijeka", "latitude" => 45.3271, "longitude" => 14.4422, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Osijek", "latitude" => 45.5511, "longitude" => 18.6939, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Zadar", "latitude" => 44.1194, "longitude" => 15.2314, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Pula", "latitude" => 44.8666, "longitude" => 13.8496, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Slavonski Brod", "latitude" => 45.1603, "longitude" => 18.0156, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Karlovac", "latitude" => 45.4872, "longitude" => 15.5476, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Varaždin", "latitude" => 46.3057, "longitude" => 16.3366, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Dubrovnik", "latitude" => 42.6403, "longitude" => 18.1083, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Šibenik", "latitude" => 43.7350, "longitude" => 15.8934, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Čakovec", "latitude" => 46.3843, "longitude" => 16.4331, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Koprivnica", "latitude" => 46.1628, "longitude" => 16.8279, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Vinkovci", "latitude" => 45.2884, "longitude" => 18.8043, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Vukovar", "latitude" => 45.3515, "longitude" => 19.0033, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Sisak", "latitude" => 45.4875, "longitude" => 16.3753, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Bjelovar", "latitude" => 45.8980, "longitude" => 16.8489, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Petrinja", "latitude" => 45.4372, "longitude" => 16.2906, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Velika Gorica", "latitude" => 45.7126, "longitude" => 16.0764, "country" => CountryFixtures::COUNTRY_CROATIA],
            ["name" => "Samobor", "latitude" => 45.8030, "longitude" => 15.7180, "country" => CountryFixtures::COUNTRY_CROATIA],

            // Serbia
            ["name" => "Belgrade", "latitude" => 44.7866, "longitude" => 20.4489, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Novi Sad", "latitude" => 45.2671, "longitude" => 19.8335, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Niš", "latitude" => 43.3214, "longitude" => 21.8958, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Kragujevac", "latitude" => 44.0128, "longitude" => 20.9114, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Subotica", "latitude" => 46.0983, "longitude" => 19.6700, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Zrenjanin", "latitude" => 45.3833, "longitude" => 20.3888, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Pančevo", "latitude" => 44.8708, "longitude" => 20.6456, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Smederevo", "latitude" => 44.6633, "longitude" => 20.9319, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Čačak", "latitude" => 43.8914, "longitude" => 20.3497, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Leskovac", "latitude" => 42.9981, "longitude" => 21.9464, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Kraljevo", "latitude" => 43.7258, "longitude" => 20.6891, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Vranje", "latitude" => 42.5514, "longitude" => 21.9003, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Valjevo", "latitude" => 44.2728, "longitude" => 19.8844, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Pirot", "latitude" => 43.1553, "longitude" => 22.5850, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Šabac", "latitude" => 44.7558, "longitude" => 19.6936, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Sombor", "latitude" => 45.7742, "longitude" => 19.1124, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Loznica", "latitude" => 44.5351, "longitude" => 19.2259, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Užice", "latitude" => 43.8578, "longitude" => 19.8480, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Novi Pazar", "latitude" => 43.1370, "longitude" => 20.5146, "country" => CountryFixtures::COUNTRY_SERBIA],
            ["name" => "Jagodina", "latitude" => 43.9751, "longitude" => 21.2602, "country" => CountryFixtures::COUNTRY_SERBIA],

            // Slovenia
            ["name" => "Ljubljana", "latitude" => 46.0569, "longitude" => 14.5058, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Maribor", "latitude" => 46.5547, "longitude" => 15.6459, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Celje", "latitude" => 46.2309, "longitude" => 15.2604, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Kranj", "latitude" => 46.2389, "longitude" => 14.3556, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Velenje", "latitude" => 46.3592, "longitude" => 15.1106, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Koper", "latitude" => 45.5469, "longitude" => 13.7294, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Novo Mesto", "latitude" => 45.8042, "longitude" => 15.1689, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Ptuj", "latitude" => 46.4197, "longitude" => 15.8706, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Trbovlje", "latitude" => 46.1531, "longitude" => 15.0478, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Murska Sobota", "latitude" => 46.6622, "longitude" => 16.1667, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Jesenice", "latitude" => 46.4314, "longitude" => 14.0666, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Domžale", "latitude" => 46.1406, "longitude" => 14.5922, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Škofja Loka", "latitude" => 46.1667, "longitude" => 14.3000, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Nova Gorica", "latitude" => 45.9576, "longitude" => 13.6435, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Ravne na Koroškem", "latitude" => 46.5431, "longitude" => 14.9697, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Idrija", "latitude" => 46.0017, "longitude" => 14.0308, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Sežana", "latitude" => 45.7053, "longitude" => 13.8704, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Litija", "latitude" => 46.0586, "longitude" => 14.8247, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Slovenj Gradec", "latitude" => 46.5103, "longitude" => 15.0806, "country" => CountryFixtures::COUNTRY_SLOVENIA],
            ["name" => "Piran", "latitude" => 45.5285, "longitude" => 13.5687, "country" => CountryFixtures::COUNTRY_SLOVENIA],

            // Germany
            ["name" => "Berlin", "latitude" => 52.5200, "longitude" => 13.4050, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Munich", "latitude" => 48.1351, "longitude" => 11.5820, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Frankfurt", "latitude" => 50.1109, "longitude" => 8.6821, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Hamburg", "latitude" => 53.5511, "longitude" => 9.9937, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Cologne", "latitude" => 50.9375, "longitude" => 6.9603, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Stuttgart", "latitude" => 48.7758, "longitude" => 9.1829, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Düsseldorf", "latitude" => 51.2277, "longitude" => 6.7735, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Leipzig", "latitude" => 51.3397, "longitude" => 12.3731, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Dortmund", "latitude" => 51.5139, "longitude" => 7.4653, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Essen", "latitude" => 51.4556, "longitude" => 7.0116, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Bremen", "latitude" => 53.0793, "longitude" => 8.8017, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Dresden", "latitude" => 51.0504, "longitude" => 13.7373, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Hannover", "latitude" => 52.3759, "longitude" => 9.7320, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Nuremberg", "latitude" => 49.4521, "longitude" => 11.0767, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Duisburg", "latitude" => 51.4344, "longitude" => 6.7623, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Bochum", "latitude" => 51.4818, "longitude" => 7.2162, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Wuppertal", "latitude" => 51.2562, "longitude" => 7.1508, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Bielefeld", "latitude" => 52.0302, "longitude" => 8.5325, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Bonn", "latitude" => 50.7374, "longitude" => 7.0982, "country" => CountryFixtures::COUNTRY_GERMANY],
            ["name" => "Mannheim", "latitude" => 49.4875, "longitude" => 8.4660, "country" => CountryFixtures::COUNTRY_GERMANY],

            // France
            ["name" => "Paris", "latitude" => 48.8566, "longitude" => 2.3522, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Marseille", "latitude" => 43.2965, "longitude" => 5.3698, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Lyon", "latitude" => 45.7640, "longitude" => 4.8357, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Toulouse", "latitude" => 43.6047, "longitude" => 1.4442, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Nice", "latitude" => 43.7102, "longitude" => 7.2620, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Nantes", "latitude" => 47.2184, "longitude" => -1.5536, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Strasbourg", "latitude" => 48.5734, "longitude" => 7.7521, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Montpellier", "latitude" => 43.6108, "longitude" => 3.8767, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Bordeaux", "latitude" => 44.8378, "longitude" => -0.5792, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Lille", "latitude" => 50.6292, "longitude" => 3.0573, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Rennes", "latitude" => 48.1173, "longitude" => -1.6778, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Reims", "latitude" => 49.2583, "longitude" => 4.0317, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Le Havre", "latitude" => 49.4944, "longitude" => 0.1079, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Saint-Étienne", "latitude" => 45.4397, "longitude" => 4.3872, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Toulon", "latitude" => 43.1242, "longitude" => 5.9280, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Angers", "latitude" => 47.4784, "longitude" => -0.5632, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Grenoble", "latitude" => 45.1885, "longitude" => 5.7245, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Dijon", "latitude" => 47.3220, "longitude" => 5.0415, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Nîmes", "latitude" => 43.8367, "longitude" => 4.3601, "country" => CountryFixtures::COUNTRY_FRANCE],
            ["name" => "Aix-en-Provence", "latitude" => 43.5297, "longitude" => 5.4474, "country" => CountryFixtures::COUNTRY_FRANCE],

            // Netherlands
            ["name" => "Amsterdam", "latitude" => 52.3676, "longitude" => 4.9041, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Rotterdam", "latitude" => 51.9225, "longitude" => 4.4792, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "The Hague", "latitude" => 52.0705, "longitude" => 4.3007, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Utrecht", "latitude" => 52.0907, "longitude" => 5.1214, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Eindhoven", "latitude" => 51.4416, "longitude" => 5.4697, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Tilburg", "latitude" => 51.5555, "longitude" => 5.0913, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Groningen", "latitude" => 53.2194, "longitude" => 6.5665, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Almere", "latitude" => 52.3508, "longitude" => 5.2647, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Breda", "latitude" => 51.5719, "longitude" => 4.7683, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Nijmegen", "latitude" => 51.8420, "longitude" => 5.8528, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Enschede", "latitude" => 52.2215, "longitude" => 6.8937, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Apeldoorn", "latitude" => 52.2112, "longitude" => 5.9699, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Haarlem", "latitude" => 52.3874, "longitude" => 4.6462, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Amersfoort", "latitude" => 52.1561, "longitude" => 5.3878, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Arnhem", "latitude" => 51.9851, "longitude" => 5.8987, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Zaanstad", "latitude" => 52.4579, "longitude" => 4.7510, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Hertogenbosch", "latitude" => 51.6978, "longitude" => 5.3037, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Zwolle", "latitude" => 52.5128, "longitude" => 6.0944, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Leiden", "latitude" => 52.1601, "longitude" => 4.4970, "country" => CountryFixtures::COUNTRY_NETHERLANDS],
            ["name" => "Maastricht", "latitude" => 50.8514, "longitude" => 5.6900, "country" => CountryFixtures::COUNTRY_NETHERLANDS],

            // Italy
            ["name" => "Rome", "latitude" => 41.9028, "longitude" => 12.4964, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Milan", "latitude" => 45.4642, "longitude" => 9.1900, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Naples", "latitude" => 40.8518, "longitude" => 14.2681, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Turin", "latitude" => 45.0703, "longitude" => 7.6869, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Palermo", "latitude" => 38.1157, "longitude" => 13.3615, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Genoa", "latitude" => 44.4056, "longitude" => 8.9463, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Bologna", "latitude" => 44.4949, "longitude" => 11.3426, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Florence", "latitude" => 43.7696, "longitude" => 11.2558, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Bari", "latitude" => 41.1171, "longitude" => 16.8719, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Verona", "latitude" => 45.4384, "longitude" => 10.9916, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Venice", "latitude" => 45.4408, "longitude" => 12.3155, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Messina", "latitude" => 38.1938, "longitude" => 15.5540, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Padua", "latitude" => 45.4064, "longitude" => 11.8768, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Trieste", "latitude" => 45.6495, "longitude" => 13.7768, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Taranto", "latitude" => 40.4644, "longitude" => 17.2470, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Brescia", "latitude" => 45.5416, "longitude" => 10.2118, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Prato", "latitude" => 43.8802, "longitude" => 11.0966, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Parma", "latitude" => 44.8015, "longitude" => 10.3279, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Modena", "latitude" => 44.6471, "longitude" => 10.9252, "country" => CountryFixtures::COUNTRY_ITALY],
            ["name" => "Reggio Emilia", "latitude" => 44.6983, "longitude" => 10.6312, "country" => CountryFixtures::COUNTRY_ITALY],

            // Spain
            ["name" => "Madrid", "latitude" => 40.4168, "longitude" => -3.7038, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Barcelona", "latitude" => 41.3851, "longitude" => 2.1734, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Valencia", "latitude" => 39.4699, "longitude" => -0.3763, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Seville", "latitude" => 37.3886, "longitude" => -5.9823, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Zaragoza", "latitude" => 41.6498, "longitude" => -0.8891, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Málaga", "latitude" => 36.7213, "longitude" => -4.4214, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Murcia", "latitude" => 37.9834, "longitude" => -1.1299, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Palma", "latitude" => 39.5696, "longitude" => 2.6502, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Las Palmas", "latitude" => 28.1235, "longitude" => -15.4363, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Bilbao", "latitude" => 43.2630, "longitude" => -2.9349, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Alicante", "latitude" => 38.3452, "longitude" => -0.4810, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Córdoba", "latitude" => 37.8882, "longitude" => -4.7794, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Valladolid", "latitude" => 41.6523, "longitude" => -4.7245, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Vigo", "latitude" => 42.2406, "longitude" => -8.7207, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Gijón", "latitude" => 43.5322, "longitude" => -5.6611, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "L'Hospitalet de Llobregat", "latitude" => 41.3662, "longitude" => 2.1169, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "A Coruña", "latitude" => 43.3623, "longitude" => -8.4115, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Vitoria-Gasteiz", "latitude" => 42.8464, "longitude" => -2.6716, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Granada", "latitude" => 37.1773, "longitude" => -3.5986, "country" => CountryFixtures::COUNTRY_SPAIN],
            ["name" => "Tarragona", "latitude" => 41.1189, "longitude" => 1.2455, "country" => CountryFixtures::COUNTRY_SPAIN],

            // Poland
            ["name" => "Warsaw", "latitude" => 52.2297, "longitude" => 21.0122, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Kraków", "latitude" => 50.0647, "longitude" => 19.9450, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Łódź", "latitude" => 51.7592, "longitude" => 19.4560, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Wrocław", "latitude" => 51.1079, "longitude" => 17.0385, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Poznań", "latitude" => 52.4064, "longitude" => 16.9252, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Gdańsk", "latitude" => 54.3520, "longitude" => 18.6466, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Szczecin", "latitude" => 53.4285, "longitude" => 14.5528, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Bydgoszcz", "latitude" => 53.1235, "longitude" => 18.0084, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Lublin", "latitude" => 51.2465, "longitude" => 22.5684, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Katowice", "latitude" => 50.2649, "longitude" => 19.0238, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Białystok", "latitude" => 53.1325, "longitude" => 23.1688, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Gdynia", "latitude" => 54.5189, "longitude" => 18.5305, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Częstochowa", "latitude" => 50.8118, "longitude" => 19.1203, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Radom", "latitude" => 51.4027, "longitude" => 21.1471, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Toruń", "latitude" => 53.0138, "longitude" => 18.5984, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Kielce", "latitude" => 50.8661, "longitude" => 20.6286, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Rzeszów", "latitude" => 50.0413, "longitude" => 21.9990, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Gliwice", "latitude" => 50.2945, "longitude" => 18.6714, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Zabrze", "latitude" => 50.3249, "longitude" => 18.7857, "country" => CountryFixtures::COUNTRY_POLAND],
            ["name" => "Olsztyn", "latitude" => 53.7784, "longitude" => 20.4801, "country" => CountryFixtures::COUNTRY_POLAND],

            // Austria
            ["name" => "Vienna", "latitude" => 48.2082, "longitude" => 16.3738, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Graz", "latitude" => 47.0707, "longitude" => 15.4395, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Linz", "latitude" => 48.3069, "longitude" => 14.2858, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Salzburg", "latitude" => 47.7982, "longitude" => 13.0460, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Innsbruck", "latitude" => 47.2682, "longitude" => 11.3923, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Klagenfurt", "latitude" => 46.6249, "longitude" => 14.3050, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Villach", "latitude" => 46.6103, "longitude" => 13.8558, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Wels", "latitude" => 48.1575, "longitude" => 14.0289, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Sankt Pölten", "latitude" => 48.2047, "longitude" => 15.6266, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Dornbirn", "latitude" => 47.4125, "longitude" => 9.7417, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Steyr", "latitude" => 48.0424, "longitude" => 14.4214, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Feldkirch", "latitude" => 47.2331, "longitude" => 9.6000, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Bregenz", "latitude" => 47.5031, "longitude" => 9.7471, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Leoben", "latitude" => 47.3811, "longitude" => 15.0935, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Wiener Neustadt", "latitude" => 47.8156, "longitude" => 16.2422, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Kapfenberg", "latitude" => 47.4447, "longitude" => 15.3077, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Baden", "latitude" => 48.0067, "longitude" => 16.2325, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Hallein", "latitude" => 47.6853, "longitude" => 13.0993, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Saalfelden", "latitude" => 47.4264, "longitude" => 12.8467, "country" => CountryFixtures::COUNTRY_AUSTRIA],
            ["name" => "Krems an der Donau", "latitude" => 48.4107, "longitude" => 15.6066, "country" => CountryFixtures::COUNTRY_AUSTRIA],

            // Hungary
            ["name" => "Budapest", "latitude" => 47.4979, "longitude" => 19.0402, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Debrecen", "latitude" => 47.5316, "longitude" => 21.6273, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Szeged", "latitude" => 46.2530, "longitude" => 20.1414, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Miskolc", "latitude" => 48.1035, "longitude" => 20.7784, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Pécs", "latitude" => 46.0727, "longitude" => 18.2323, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Győr", "latitude" => 47.6875, "longitude" => 17.6504, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Nyíregyháza", "latitude" => 47.9495, "longitude" => 21.7246, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Kecskemét", "latitude" => 46.8964, "longitude" => 19.6897, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Székesfehérvár", "latitude" => 47.1860, "longitude" => 18.4221, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Szombathely", "latitude" => 47.2307, "longitude" => 16.6218, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Eger", "latitude" => 47.9025, "longitude" => 20.3772, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Nagykanizsa", "latitude" => 46.4533, "longitude" => 16.9874, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Dunaújváros", "latitude" => 46.9807, "longitude" => 18.9351, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Hódmezővásárhely", "latitude" => 46.4169, "longitude" => 20.3224, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Sopron", "latitude" => 47.6852, "longitude" => 16.5845, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Tatabánya", "latitude" => 47.5880, "longitude" => 18.3973, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Zalaegerszeg", "latitude" => 46.8432, "longitude" => 16.8514, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Kaposvár", "latitude" => 46.3594, "longitude" => 17.7968, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Békéscsaba", "latitude" => 46.6810, "longitude" => 21.0911, "country" => CountryFixtures::COUNTRY_HUNGARY],
            ["name" => "Veszprém", "latitude" => 47.0921, "longitude" => 17.9093, "country" => CountryFixtures::COUNTRY_HUNGARY],

            // Romania
            ["name" => "Bucharest", "latitude" => 44.4268, "longitude" => 26.1025, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Cluj-Napoca", "latitude" => 46.7712, "longitude" => 23.6236, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Timișoara", "latitude" => 45.7489, "longitude" => 21.2087, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Iași", "latitude" => 47.1585, "longitude" => 27.6014, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Constanța", "latitude" => 44.1598, "longitude" => 28.6348, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Craiova", "latitude" => 44.3302, "longitude" => 23.7949, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Brașov", "latitude" => 45.6579, "longitude" => 25.6012, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Galați", "latitude" => 45.4353, "longitude" => 28.0079, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Ploiești", "latitude" => 44.9387, "longitude" => 26.0226, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Oradea", "latitude" => 47.0722, "longitude" => 21.9219, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Brăila", "latitude" => 45.2719, "longitude" => 27.9739, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Arad", "latitude" => 46.1866, "longitude" => 21.3123, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Pitești", "latitude" => 44.8565, "longitude" => 24.8692, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Sibiu", "latitude" => 45.7983, "longitude" => 24.1256, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Bacău", "latitude" => 46.5671, "longitude" => 26.9133, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Târgu Mureș", "latitude" => 46.5456, "longitude" => 24.5625, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Baia Mare", "latitude" => 47.6561, "longitude" => 23.5680, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Buzău", "latitude" => 45.1517, "longitude" => 26.8234, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Satu Mare", "latitude" => 47.7928, "longitude" => 22.8856, "country" => CountryFixtures::COUNTRY_ROMANIA],
            ["name" => "Râmnicu Vâlcea", "latitude" => 45.1053, "longitude" => 24.3755, "country" => CountryFixtures::COUNTRY_ROMANIA],

            // Portugal
            ["name" => "Lisbon", "latitude" => 38.7169, "longitude" => -9.1399, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Porto", "latitude" => 41.1496, "longitude" => -8.6110, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Braga", "latitude" => 41.5454, "longitude" => -8.4265, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Coimbra", "latitude" => 40.2110, "longitude" => -8.4292, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Funchal", "latitude" => 32.6659, "longitude" => -16.9241, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Aveiro", "latitude" => 40.6405, "longitude" => -8.6538, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Guimarães", "latitude" => 41.4442, "longitude" => -8.2962, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Évora", "latitude" => 38.5667, "longitude" => -7.9000, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Vila Nova de Gaia", "latitude" => 41.1240, "longitude" => -8.6124, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Setúbal", "latitude" => 38.5244, "longitude" => -8.8882, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Faro", "latitude" => 37.0179, "longitude" => -7.9307, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Leiria", "latitude" => 39.7436, "longitude" => -8.8070, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Cascais", "latitude" => 38.6971, "longitude" => -9.4223, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Portimão", "latitude" => 37.1386, "longitude" => -8.5378, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Viseu", "latitude" => 40.6610, "longitude" => -7.9097, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Ponta Delgada", "latitude" => 37.7394, "longitude" => -25.6687, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Barcelos", "latitude" => 41.5380, "longitude" => -8.6153, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Bragança", "latitude" => 41.8062, "longitude" => -6.7552, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Tomar", "latitude" => 39.6039, "longitude" => -8.4092, "country" => CountryFixtures::COUNTRY_PORTUGAL],
            ["name" => "Lagos", "latitude" => 37.1020, "longitude" => -8.6742, "country" => CountryFixtures::COUNTRY_PORTUGAL],

            // Greece
            ["name" => "Athens", "latitude" => 37.9838, "longitude" => 23.7275, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Thessaloniki", "latitude" => 40.6401, "longitude" => 22.9444, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Patras", "latitude" => 38.2466, "longitude" => 21.7346, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Heraklion", "latitude" => 35.3387, "longitude" => 25.1442, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Larissa", "latitude" => 39.6403, "longitude" => 22.4139, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Volos", "latitude" => 39.3667, "longitude" => 22.9333, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Ioannina", "latitude" => 39.6679, "longitude" => 20.8509, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Chania", "latitude" => 35.5138, "longitude" => 24.0180, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Rhodes", "latitude" => 36.4349, "longitude" => 28.2170, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Agrinio", "latitude" => 38.6219, "longitude" => 21.4061, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Kavala", "latitude" => 40.9396, "longitude" => 24.4128, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Tripoli", "latitude" => 37.5085, "longitude" => 22.3792, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Lamia", "latitude" => 38.9000, "longitude" => 22.4333, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Kalamata", "latitude" => 37.0389, "longitude" => 22.1142, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Serres", "latitude" => 41.0845, "longitude" => 23.5415, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Alexandroupoli", "latitude" => 40.8489, "longitude" => 25.8744, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Katerini", "latitude" => 40.2726, "longitude" => 22.5028, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Chalkida", "latitude" => 38.4636, "longitude" => 23.6026, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Rethymno", "latitude" => 35.3669, "longitude" => 24.4719, "country" => CountryFixtures::COUNTRY_GREECE],
            ["name" => "Mytilene", "latitude" => 39.1107, "longitude" => 26.5548, "country" => CountryFixtures::COUNTRY_GREECE],

            // Bulgaria
            ["name" => "Sofia", "latitude" => 42.6977, "longitude" => 23.3242, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Plovdiv", "latitude" => 42.1354, "longitude" => 24.7453, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Varna", "latitude" => 43.2141, "longitude" => 27.9147, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Burgas", "latitude" => 42.5048, "longitude" => 27.4626, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Ruse", "latitude" => 43.8356, "longitude" => 25.9657, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Stara Zagora", "latitude" => 42.4258, "longitude" => 25.6345, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Pleven", "latitude" => 43.4170, "longitude" => 24.6067, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Sliven", "latitude" => 42.6814, "longitude" => 26.3229, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Dobrich", "latitude" => 43.5726, "longitude" => 27.8272, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Shumen", "latitude" => 43.2702, "longitude" => 26.9229, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Pernik", "latitude" => 42.6106, "longitude" => 23.0300, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Haskovo", "latitude" => 41.9341, "longitude" => 25.5550, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Yambol", "latitude" => 42.4833, "longitude" => 26.5031, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Blagoevgrad", "latitude" => 42.0209, "longitude" => 23.0948, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Veliko Tarnovo", "latitude" => 43.0810, "longitude" => 25.6290, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Vidin", "latitude" => 43.9937, "longitude" => 22.8725, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Kazanlak", "latitude" => 42.6163, "longitude" => 25.3934, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Asenovgrad", "latitude" => 42.0144, "longitude" => 24.8723, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Vratsa", "latitude" => 43.2105, "longitude" => 23.5520, "country" => CountryFixtures::COUNTRY_BULGARIA],
            ["name" => "Kardzhali", "latitude" => 41.6530, "longitude" => 25.3669, "country" => CountryFixtures::COUNTRY_BULGARIA],

            // Czech Republic
            ["name" => "Prague", "latitude" => 50.0755, "longitude" => 14.4378, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Brno", "latitude" => 49.1951, "longitude" => 16.6068, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Ostrava", "latitude" => 49.8347, "longitude" => 18.2920, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Plzeň", "latitude" => 49.7475, "longitude" => 13.3776, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Liberec", "latitude" => 50.7671, "longitude" => 15.0562, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Olomouc", "latitude" => 49.5955, "longitude" => 17.2518, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "České Budějovice", "latitude" => 48.9757, "longitude" => 14.4803, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Hradec Králové", "latitude" => 50.2092, "longitude" => 15.8328, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Ústí nad Labem", "latitude" => 50.6606, "longitude" => 14.0410, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Pardubice", "latitude" => 50.0389, "longitude" => 15.7812, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Zlín", "latitude" => 49.2236, "longitude" => 17.6740, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Havířov", "latitude" => 49.7792, "longitude" => 18.4301, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Kladno", "latitude" => 50.1471, "longitude" => 14.1027, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Most", "latitude" => 50.5033, "longitude" => 13.6363, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Karviná", "latitude" => 49.8547, "longitude" => 18.5410, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Opava", "latitude" => 49.9389, "longitude" => 17.9025, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Frýdek-Místek", "latitude" => 49.6843, "longitude" => 18.3485, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Teplice", "latitude" => 50.6403, "longitude" => 13.8243, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Jihlava", "latitude" => 49.3967, "longitude" => 15.5906, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],
            ["name" => "Karlovy Vary", "latitude" => 50.2327, "longitude" => 12.8717, "country" => CountryFixtures::COUNTRY_CZECH_REPUBLIC],

            // Belgium
            ["name" => "Brussels", "latitude" => 50.8503, "longitude" => 4.3517, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Antwerp", "latitude" => 51.2194, "longitude" => 4.4025, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Ghent", "latitude" => 51.0543, "longitude" => 3.7174, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Charleroi", "latitude" => 50.4114, "longitude" => 4.4445, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Liège", "latitude" => 50.6451, "longitude" => 5.5734, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Bruges", "latitude" => 51.2093, "longitude" => 3.2247, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Namur", "latitude" => 50.4674, "longitude" => 4.8710, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Leuven", "latitude" => 50.8798, "longitude" => 4.7005, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Mons", "latitude" => 50.4542, "longitude" => 3.9523, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Aalst", "latitude" => 50.9360, "longitude" => 4.0355, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Mechelen", "latitude" => 51.0257, "longitude" => 4.4777, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Kortrijk", "latitude" => 50.8260, "longitude" => 3.2649, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Hasselt", "latitude" => 50.9311, "longitude" => 5.3378, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Ostend", "latitude" => 51.2302, "longitude" => 2.9123, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Sint-Niklaas", "latitude" => 51.1643, "longitude" => 4.1390, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Tournai", "latitude" => 50.6071, "longitude" => 3.3895, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Genk", "latitude" => 50.9665, "longitude" => 5.5000, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Roeselare", "latitude" => 50.9448, "longitude" => 3.1230, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Verviers", "latitude" => 50.5929, "longitude" => 5.8624, "country" => CountryFixtures::COUNTRY_BELGIUM],
            ["name" => "Mouscron", "latitude" => 50.7400, "longitude" => 3.2066, "country" => CountryFixtures::COUNTRY_BELGIUM],

            // Lithuania
            ["name" => "Vilnius", "latitude" => 54.6872, "longitude" => 25.2797, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Kaunas", "latitude" => 54.8985, "longitude" => 23.9036, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Klaipėda", "latitude" => 55.7033, "longitude" => 21.1443, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Šiauliai", "latitude" => 55.9333, "longitude" => 23.3167, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Panevėžys", "latitude" => 55.7333, "longitude" => 24.3500, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Alytus", "latitude" => 54.4010, "longitude" => 24.0418, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Marijampolė", "latitude" => 54.5562, "longitude" => 23.3514, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Mažeikiai", "latitude" => 56.3167, "longitude" => 22.3333, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Jonava", "latitude" => 55.0833, "longitude" => 24.2833, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Utena", "latitude" => 55.5000, "longitude" => 25.6000, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Telšiai", "latitude" => 55.9866, "longitude" => 22.2489, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Visaginas", "latitude" => 55.5966, "longitude" => 26.4399, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Tauragė", "latitude" => 55.2522, "longitude" => 22.2903, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Ukmergė", "latitude" => 55.2500, "longitude" => 24.7500, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Kėdainiai", "latitude" => 55.2889, "longitude" => 23.9725, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Radviliškis", "latitude" => 55.8167, "longitude" => 23.5333, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Palanga", "latitude" => 55.9200, "longitude" => 21.0700, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Druskininkai", "latitude" => 54.0167, "longitude" => 23.9667, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Biržai", "latitude" => 56.2000, "longitude" => 24.7500, "country" => CountryFixtures::COUNTRY_LITHUANIA],
            ["name" => "Šilutė", "latitude" => 55.3481, "longitude" => 21.4647, "country" => CountryFixtures::COUNTRY_LITHUANIA],

            // Denmark
            ["name" => "Copenhagen", "latitude" => 55.6761, "longitude" => 12.5683, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Aarhus", "latitude" => 56.1629, "longitude" => 10.2039, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Odense", "latitude" => 55.4038, "longitude" => 10.4024, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Aalborg", "latitude" => 57.0488, "longitude" => 9.9217, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Esbjerg", "latitude" => 55.4765, "longitude" => 8.4594, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Randers", "latitude" => 56.4607, "longitude" => 10.0364, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Kolding", "latitude" => 55.4904, "longitude" => 9.4722, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Horsens", "latitude" => 55.8607, "longitude" => 9.8503, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Vejle", "latitude" => 55.7113, "longitude" => 9.5368, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Roskilde", "latitude" => 55.6419, "longitude" => 12.0878, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Herning", "latitude" => 56.1393, "longitude" => 8.9730, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Helsingør", "latitude" => 56.0361, "longitude" => 12.6116, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Silkeborg", "latitude" => 56.1697, "longitude" => 9.5451, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Næstved", "latitude" => 55.2290, "longitude" => 11.7609, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Fredericia", "latitude" => 55.5657, "longitude" => 9.7526, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Viborg", "latitude" => 56.4537, "longitude" => 9.4020, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Køge", "latitude" => 55.4580, "longitude" => 12.1836, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Holstebro", "latitude" => 56.3609, "longitude" => 8.6188, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Slagelse", "latitude" => 55.4020, "longitude" => 11.3545, "country" => CountryFixtures::COUNTRY_DENMARK],
            ["name" => "Hjørring", "latitude" => 57.4644, "longitude" => 9.9827, "country" => CountryFixtures::COUNTRY_DENMARK],

            // Latvia
            ["name" => "Riga", "latitude" => 56.9496, "longitude" => 24.1052, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Daugavpils", "latitude" => 55.8755, "longitude" => 26.5359, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Liepāja", "latitude" => 56.5091, "longitude" => 21.0135, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Jelgava", "latitude" => 56.6524, "longitude" => 23.7189, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Jūrmala", "latitude" => 56.9668, "longitude" => 23.7509, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Ventspils", "latitude" => 57.3894, "longitude" => 21.5606, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Rēzekne", "latitude" => 56.5087, "longitude" => 27.3383, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Valmiera", "latitude" => 57.5410, "longitude" => 25.4273, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Ogre", "latitude" => 56.8169, "longitude" => 24.6140, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Cēsis", "latitude" => 57.3119, "longitude" => 25.2712, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Tukums", "latitude" => 56.9667, "longitude" => 23.1559, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Kuldīga", "latitude" => 56.9678, "longitude" => 21.9707, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Saldus", "latitude" => 56.6633, "longitude" => 22.4892, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Madona", "latitude" => 56.8544, "longitude" => 26.2196, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Aizkraukle", "latitude" => 56.6047, "longitude" => 25.2602, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Talsi", "latitude" => 57.2457, "longitude" => 22.5868, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Ludza", "latitude" => 56.5481, "longitude" => 27.7276, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Dobele", "latitude" => 56.6250, "longitude" => 23.2792, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Bauska", "latitude" => 56.4079, "longitude" => 24.1902, "country" => CountryFixtures::COUNTRY_LATVIA],
            ["name" => "Sigulda", "latitude" => 57.1526, "longitude" => 24.8608, "country" => CountryFixtures::COUNTRY_LATVIA],
        ];

        foreach ($citiesData as $index => $cityData) {
            $city = new City();
            $city->setCountry($this->getReference($cityData["country"], Country::class));
            $city->setName($cityData["name"]);
            $city->setLatitude($cityData["latitude"]);
            $city->setLongitude($cityData["longitude"]);
            $manager->persist($city);

            if ($index === 0) {
                $this->addReference(self::CITY_ZAGREB, $city);
            }
        }

        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            CountryFixtures::class,
        ];
    }
}
